# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosti',
            name='bacon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tosti',
            name='bread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tosti',
            name='cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tosti',
            name='ham',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tosti',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tosti',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tosti',
            name='tomato',
            field=models.IntegerField(default=0),
        ),
    ]
